name: "Docs Linting:"
on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  prose:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Vale Linter
      uses: errata-ai/vale-action@v1.3.0
      with:
        config: ../../.valepush.ini
        # Optional
        files: website/content/docs
      env:
        # Required
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
