name: Push Test
on: [push]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Docs
      uses: errata-ai/vale-action@v1.3.0
      with:
        # Optional
        files: website/content/docs
      env:
        # Required
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
