name: Linting
on: [push]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Vale
      uses: errata-ai/vale-action@v1.3.0
      with:
        # Optional
        styles: |
          .vale/styles/netlify
          .vale/styles/write-good

        # Optional
        files: website/content/docs
      env:
        # Required
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
